# This workflow will do a clean install of Node dependencies, cache/restore them,
# build Storybook as a static web application, and deploy it to the gh-pages branch.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy Storybook

on:
  # Currently set to run on every push to main, but in the future
  # we may want to restrict it to running on every new release.
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Node ⬢
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies 🧱
        run: npm ci

      - name: Build static Storybook 🛠
        run: npm run build-storybook
      
        # https://github.com/JamesIves/github-pages-deploy-action/issues/1475#issuecomment-1824079512
      - name: Add nojekyll file to read underscore files 📋
        run: cd storybook_compiled && touch .nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook_compiled
          branch: gh-pages
